title: Marcos Pereira Jr
description: >
  **Marcos Pereira Jr**
subdescription: Engenheiro de Software na Agriness
local: Florianópolis/SC
copyright: Marcos Pereira
sass:
  sass_dir: assets/sass
url: http://marcospereirajr.com.br
disqus_shortname: "http-marcospereirajr-com-br"
facebook_username: "marcospereira.mpj"
twitter_username: "_marcos_pereira"
linkedin_username: "marcospereirampj"
instagram_username: "marcospereira_mpj"
pinterest_username:
flickr_username:
github_username:  "marcospereirampj"
feed_icon: rss
email: "marcospereira.mpj@gmail.com"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
